// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EyzD5FLnWcGmjaMjS-Ofk32dLAzP3Bs',
    appId: '1:1072910830136:web:9b7afcbf19dd35f316f4cd',
    messagingSenderId: '1072910830136',
    projectId: 'onesmart-d8635',
    authDomain: 'onesmart-d8635.firebaseapp.com',
    storageBucket: 'onesmart-d8635.firebasestorage.app',
    measurementId: 'G-QB20N9ZK7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV7F5ppQoDmhnbtCXaZCSKAVqtrgIBy7s',
    appId: '1:1072910830136:android:06c5395dc635416a16f4cd',
    messagingSenderId: '1072910830136',
    projectId: 'onesmart-d8635',
    storageBucket: 'onesmart-d8635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcTJH66WwN2HroZBSamIZM5LVvU__nQU',
    appId: '1:1072910830136:ios:3b1e3beb5a08597716f4cd',
    messagingSenderId: '1072910830136',
    projectId: 'onesmart-d8635',
    storageBucket: 'onesmart-d8635.firebasestorage.app',
    iosBundleId: 'com.example.oneSmartShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcTJH66WwN2HroZBSamIZM5LVvU__nQU',
    appId: '1:1072910830136:ios:3b1e3beb5a08597716f4cd',
    messagingSenderId: '1072910830136',
    projectId: 'onesmart-d8635',
    storageBucket: 'onesmart-d8635.firebasestorage.app',
    iosBundleId: 'com.example.oneSmartShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp4oW-acILQnLI67NBeBZYnr2ptAcF2PM',
    appId: '1:261394922335:web:94d8f9b9c12c60a73fd4ea',
    messagingSenderId: '261394922335',
    projectId: 'one-smart-shop',
    authDomain: 'one-smart-shop.firebaseapp.com',
    storageBucket: 'one-smart-shop.firebasestorage.app',
    measurementId: 'G-ZCGS91C1GM',
  );

}